apiVersion: v1
kind: Pod 
metadata: 
  name: myapp
  labels:
    env : myapp
spec:
  containers: 
  - name: myapp-container
    image: nginx
    env:
    - name: KEYSECRET
      value: "token124"
    command: ['sh', '-c']
    args: ['curl myapp-svc.default.svc.cluster.local && sleep 60']
  initContainers:
  - name: myapp-init-container
    image: nginx
    command: ['sh', '-c']
    args: ['until curl myapp-svc.default.svc.cluster.local;do echo waiting to svc up;done && sleep 2']

